[package]
name = "raytracing-rs"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "main"
path = "bin/main.rs"

[[bench]]
name = "thread"
harness = false

[profile.bench]
debug = true

[dependencies]
rand = "0.8.4"
rayon = "1.5.1"
threadpool = "1.8.1"

[dev-dependencies]
criterion = "0.3.5"
